/**
 * Simple Auction House - constants.js
 * Controls chest UI behaviour.
 */

// Namespace import on purpose: a named import of a symbol the running API does
// not expose fails the whole module with "Import [constants.js] not found" and
// takes the plugin down with it. Off the namespace, an absent symbol is just
// undefined and the count falls back to the table.
import * as mc from '@minecraft/server';

/** Set to true to show the player's own inventory below the chest grid. Increases form lag slightly. */
export const inventory_enabled = false;

/**
 * Custom item/block overrides.
 * Format: 'namespace:id': { texture: 'path/or/typeId', type: 'item' | 'block' }
 * Leave empty unless you have custom content packs installed.
 */
export const custom_content = {

	// OresPlus blocks. Their block json carries no texture reference -
	// the add-on binds them by name to a terrain_texture key
	// (oresplus:jade_ore -> oresplus_jade_ore). Typed as 'block' so they are
	// not counted as custom ITEMS in the offset.
	'oresplus:ambar_block': { texture: 'textures/blocks/ambar/ambar_block', type: 'block' },
	'oresplus:ambar_ore': { texture: 'textures/blocks/ambar/ambar_ore', type: 'block' },
	'oresplus:chiseled_rose_quartz': { texture: 'textures/blocks/rose_quartz/chiseled_rose_quartz', type: 'block' },
	'oresplus:deepslate_ambar_ore': { texture: 'textures/blocks/ambar/deepslate_ambar_ore', type: 'block' },
	'oresplus:deepslate_jade_ore': { texture: 'textures/blocks/jade/deepslate_jade_ore', type: 'block' },
	'oresplus:deepslate_moonstone_ore': { texture: 'textures/blocks/moonstone/deepslate_moonstone_ore', type: 'block' },
	'oresplus:deepslate_mythril_ore': { texture: 'textures/blocks/mythril/deepslate_mythril_ore', type: 'block' },
	'oresplus:deepslate_rose_quartz_ore': { texture: 'textures/blocks/rose_quartz/deepslate_rose_quartz_ore', type: 'block' },
	'oresplus:deepslate_ruby_ore': { texture: 'textures/blocks/ruby/deepslate_ruby_ore', type: 'block' },
	'oresplus:deepslate_sapphire_ore': { texture: 'textures/blocks/sapphire/deepslate_sapphire_ore', type: 'block' },
	'oresplus:deepslate_silver_ore': { texture: 'textures/blocks/silver/deepslate_silver_ore', type: 'block' },
	'oresplus:deepslate_tungsten_ore': { texture: 'textures/blocks/tungsten/deepslate_tungsten_ore', type: 'block' },
	'oresplus:deepslate_white_diamond_ore': { texture: 'textures/blocks/white_diamond/deepslate_white_diamond_ore', type: 'block' },
	'oresplus:jade_block': { texture: 'textures/blocks/jade/jade_block', type: 'block' },
	'oresplus:jade_ore': { texture: 'textures/blocks/jade/jade_ore', type: 'block' },
	'oresplus:limestone': { texture: 'textures/blocks/limestone/limestone', type: 'block' },
	'oresplus:limestone_bricks': { texture: 'textures/blocks/limestone/limestone_bricks', type: 'block' },
	'oresplus:limestone_coal_ore': { texture: 'textures/blocks/limestone/limestone_coal_ore', type: 'block' },
	'oresplus:limestone_copper_ore': { texture: 'textures/blocks/limestone/limestone_copper_ore', type: 'block' },
	'oresplus:limestone_diamond_ore': { texture: 'textures/blocks/limestone/limestone_diamond_ore', type: 'block' },
	'oresplus:limestone_emerald_ore': { texture: 'textures/blocks/limestone/limestone_emerald_ore', type: 'block' },
	'oresplus:limestone_gold_ore': { texture: 'textures/blocks/limestone/limestone_gold_ore', type: 'block' },
	'oresplus:limestone_iron_ore': { texture: 'textures/blocks/limestone/limestone_iron_ore', type: 'block' },
	'oresplus:limestone_lapis_ore': { texture: 'textures/blocks/limestone/limestone_lapis_ore', type: 'block' },
	'oresplus:limestone_polish': { texture: 'textures/blocks/limestone/polished_limestone', type: 'block' },
	'oresplus:limestone_redstone_ore': { texture: 'textures/blocks/limestone/limestone_redstone_ore', type: 'block' },
	'oresplus:marble': { texture: 'textures/blocks/marble/marble', type: 'block' },
	'oresplus:marble_bricks': { texture: 'textures/blocks/marble/marble_bricks', type: 'block' },
	'oresplus:marble_polish': { texture: 'textures/blocks/marble/polished_marble', type: 'block' },
	'oresplus:moonstone_block': { texture: 'textures/blocks/moonstone/moonstone_block', type: 'block' },
	'oresplus:moonstone_ore': { texture: 'textures/blocks/moonstone/moonstone_ore', type: 'block' },
	'oresplus:mythril_block': { texture: 'textures/blocks/mythril/mythril_block', type: 'block' },
	'oresplus:mythril_ore': { texture: 'textures/blocks/mythril/mythril_ore', type: 'block' },
	'oresplus:netherrack_tane_ore': { texture: 'textures/blocks/tane/netherrack_tane_ore', type: 'block' },
	'oresplus:netherrack_titanium_ore': { texture: 'textures/blocks/titanium/netherrack_titanium_ore', type: 'block' },
	'oresplus:polished_limestone': { texture: 'textures/blocks/limestone/polished_limestone', type: 'block' },
	'oresplus:polished_marble': { texture: 'textures/blocks/marble/polished_marble', type: 'block' },
	'oresplus:pyrite_block': { texture: 'textures/blocks/pyrite/pyrite_block', type: 'block' },
	'oresplus:raw_rose_gold_block': { texture: 'textures/blocks/rose_gold/raw_rose_gold_block', type: 'block' },
	'oresplus:raw_silver_block': { texture: 'textures/blocks/silver/raw_silver_block', type: 'block' },
	'oresplus:raw_tungsten_block': { texture: 'textures/blocks/tungsten/raw_tungsten_block', type: 'block' },
	'oresplus:rose_gold_block': { texture: 'textures/blocks/rose_gold/rose_gold_block', type: 'block' },
	'oresplus:rose_quartz_block': { texture: 'textures/blocks/rose_quartz/rose_quartz_block', type: 'block' },
	'oresplus:rose_quartz_bricks': { texture: 'textures/blocks/rose_quartz/rose_quartz_brick', type: 'block' },
	'oresplus:rose_quartz_ore': { texture: 'textures/blocks/rose_quartz/rose_quartz_ore', type: 'block' },
	'oresplus:rose_quartz_pillar': { texture: 'textures/blocks/rose_quartz/rose_quartz_pillar', type: 'block' },
	'oresplus:ruby_block': { texture: 'textures/blocks/ruby/ruby_block', type: 'block' },
	'oresplus:ruby_ore': { texture: 'textures/blocks/ruby/ruby_ore', type: 'block' },
	'oresplus:sapphire_block': { texture: 'textures/blocks/sapphire/sapphire_block', type: 'block' },
	'oresplus:sapphire_ore': { texture: 'textures/blocks/sapphire/sapphire_ore', type: 'block' },
	'oresplus:silver_block': { texture: 'textures/blocks/silver/silver_block', type: 'block' },
	'oresplus:silver_ore': { texture: 'textures/blocks/silver/silver_ore', type: 'block' },
	'oresplus:steel_block': { texture: 'textures/blocks/steel/steel_block', type: 'block' },
	'oresplus:tungsten_block': { texture: 'textures/blocks/tungsten/tungsten_block', type: 'block' },
	'oresplus:tungsten_ore': { texture: 'textures/blocks/tungsten/tungsten_ore', type: 'block' },
	'oresplus:viocrite': { texture: 'textures/blocks/viocrite/viocrite', type: 'block' },
	'oresplus:viocrite_bricks': { texture: 'textures/blocks/viocrite/viocrite_bricks', type: 'block' },
	'oresplus:viocrite_polish': { texture: 'textures/blocks/viocrite/viocrite_polished', type: 'block' },
	'oresplus:white_diamond_block': { texture: 'textures/blocks/white_diamond/white_diamond_block', type: 'block' },
	'oresplus:white_diamond_ore': { texture: 'textures/blocks/white_diamond/white_diamond_ore', type: 'block' },
	// â•â• vanilla â•â•
	// Texture paths, not numeric ids. forms.js turns an unpinned icon into an
	// aux id and adds number_of_custom_items to anything from 256 up; that id is
	// assigned at runtime, so it moves with the game version and with the packs
	// a world loads. A path does not move. Blocks that are also placeable items
	// belong here too - a hopper is registered as both, and dropping its pin is
	// what made it draw a green cushion.
	'minecraft:acacia_boat': { texture: 'textures/items/boat_acacia', type: 'item' },
	'minecraft:acacia_chest_boat': { texture: 'textures/items/acacia_chest_boat', type: 'item' },
	'minecraft:acacia_door': { texture: 'textures/items/door_acacia', type: 'item' },
	'minecraft:acacia_sign': { texture: 'textures/items/sign_acacia', type: 'item' },
	'minecraft:agent_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_agent', type: 'item' },
	'minecraft:allay_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_allay', type: 'item' },
	'minecraft:amethyst_shard': { texture: 'textures/items/amethyst_shard', type: 'item' },
	'minecraft:angler_pottery_sherd': { texture: 'textures/items/angler_pottery_sherd', type: 'item' },
	'minecraft:apple': { texture: 'textures/items/apple', type: 'item' },
	'minecraft:archer_pottery_sherd': { texture: 'textures/items/archer_pottery_sherd', type: 'item' },
	'minecraft:armadillo_scute': { texture: 'textures/items/armadillo_scute', type: 'item' },
	'minecraft:armadillo_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_armadillo', type: 'item' },
	'minecraft:armor_stand': { texture: 'textures/items/armor_stand', type: 'item' },
	'minecraft:arms_up_pottery_sherd': { texture: 'textures/items/arms_up_pottery_sherd', type: 'item' },
	'minecraft:arrow': { texture: 'textures/items/arrow', type: 'item' },
	'minecraft:awkward_arrow': { texture: 'textures/items/tipped_arrow', type: 'item' },
	'minecraft:awkward_lingering_potion': { texture: 'textures/items/potion_bottle_lingering', type: 'item' },
	'minecraft:awkward_potion': { texture: 'textures/items/potion_bottle_drinkable', type: 'item' },
	'minecraft:awkward_splash_potion': { texture: 'textures/items/potion_bottle_splash', type: 'item' },
	'minecraft:axolotl_bucket': { texture: 'textures/items/bucket_axolotl', type: 'item' },
	'minecraft:axolotl_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_axolotl', type: 'item' },
	'minecraft:baked_potato': { texture: 'textures/items/potato_baked', type: 'item' },
	'minecraft:bamboo_chest_raft': { texture: 'textures/items/bamboo_chest_raft', type: 'item' },
	'minecraft:bamboo_door': { texture: 'textures/items/bamboo_door', type: 'item' },
	'minecraft:bamboo_raft': { texture: 'textures/items/bamboo_raft', type: 'item' },
	'minecraft:bamboo_sign': { texture: 'textures/items/bamboo_sign', type: 'item' },
	'minecraft:banner_pattern': { texture: 'textures/items/banner_pattern', type: 'item' },
	'minecraft:bat_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_bat', type: 'item' },
	'minecraft:bed': { texture: 'textures/items/bed_white', type: 'item' },
	'minecraft:bee_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_bee', type: 'item' },
	'minecraft:beef': { texture: 'textures/items/beef_raw', type: 'item' },
	'minecraft:beetroot': { texture: 'textures/items/beetroot', type: 'item' },
	'minecraft:beetroot_seeds': { texture: 'textures/items/seeds_beetroot', type: 'item' },
	'minecraft:beetroot_soup': { texture: 'textures/items/beetroot_soup', type: 'item' },
	'minecraft:birch_boat': { texture: 'textures/items/boat_birch', type: 'item' },
	'minecraft:birch_chest_boat': { texture: 'textures/items/birch_chest_boat', type: 'item' },
	'minecraft:birch_door': { texture: 'textures/items/door_birch', type: 'item' },
	'minecraft:birch_sign': { texture: 'textures/items/sign_birch', type: 'item' },
	'minecraft:black_dye': { texture: 'textures/items/dye_powder_black', type: 'item' },
	'minecraft:blade_pottery_sherd': { texture: 'textures/items/blade_pottery_sherd', type: 'item' },
	'minecraft:blaze_powder': { texture: 'textures/items/blaze_powder', type: 'item' },
	'minecraft:blaze_rod': { texture: 'textures/items/blaze_rod', type: 'item' },
	'minecraft:blaze_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_blaze', type: 'item' },
	'minecraft:blue_dye': { texture: 'textures/items/dye_powder_blue', type: 'item' },
	'minecraft:blue_egg': { texture: 'textures/items/blue_egg', type: 'item' },
	'minecraft:boat': { texture: 'textures/items/boat_oak', type: 'item' },
	'minecraft:bogged_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_bogged', type: 'item' },
	'minecraft:bolt_armor_trim_smithing_template': { texture: 'textures/items/bolt_armor_trim_smithing_template', type: 'item' },
	'minecraft:bone': { texture: 'textures/items/bone', type: 'item' },
	'minecraft:bone_meal': { texture: 'textures/items/dye_powder_white', type: 'item' },
	'minecraft:book': { texture: 'textures/items/book_normal', type: 'item' },
	'minecraft:bordure_indented_banner_pattern': { texture: 'textures/items/bordure_indented_banner_pattern', type: 'item' },
	'minecraft:bow': { texture: 'textures/items/bow_standby', type: 'item' },
	'minecraft:bowl': { texture: 'textures/items/bowl', type: 'item' },
	'minecraft:bread': { texture: 'textures/items/bread', type: 'item' },
	'minecraft:breeze_rod': { texture: 'textures/items/breeze_rod', type: 'item' },
	'minecraft:breeze_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_breeze', type: 'item' },
	'minecraft:brewer_pottery_sherd': { texture: 'textures/items/brewer_pottery_sherd', type: 'item' },
	'minecraft:brewing_stand': { texture: 'textures/items/brewing_stand', type: 'item' },
	'minecraft:brick': { texture: 'textures/items/brick', type: 'item' },
	'minecraft:brown_dye': { texture: 'textures/items/dye_powder_brown', type: 'item' },
	'minecraft:brown_egg': { texture: 'textures/items/brown_egg', type: 'item' },
	'minecraft:brush': { texture: 'textures/items/brush', type: 'item' },
	'minecraft:bucket': { texture: 'textures/items/bucket_empty', type: 'item' },
	'minecraft:bundle': { texture: 'textures/items/bundle', type: 'item' },
	'minecraft:burn_pottery_sherd': { texture: 'textures/items/burn_pottery_sherd', type: 'item' },
	'minecraft:cake': { texture: 'textures/items/cake', type: 'item' },
	'minecraft:camel_husk_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_camel_husk', type: 'item' },
	'minecraft:camel_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_camel', type: 'item' },
	'minecraft:camera': { texture: 'textures/items/camera', type: 'item' },
	'minecraft:campfire': { texture: 'textures/items/campfire', type: 'item' },
	'minecraft:carrot': { texture: 'textures/items/carrot', type: 'item' },
	'minecraft:carrot_on_a_stick': { texture: 'textures/items/carrot_on_a_stick', type: 'item' },
	'minecraft:cat_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_cat', type: 'item' },
	'minecraft:cauldron': { texture: 'textures/items/cauldron', type: 'item' },
	'minecraft:cave_spider_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_cave_spider', type: 'item' },
	'minecraft:chainmail_boots': { texture: 'textures/items/chainmail_boots', type: 'item' },
	'minecraft:chainmail_chestplate': { texture: 'textures/items/chainmail_chestplate', type: 'item' },
	'minecraft:chainmail_helmet': { texture: 'textures/items/chainmail_helmet', type: 'item' },
	'minecraft:chainmail_leggings': { texture: 'textures/items/chainmail_leggings', type: 'item' },
	'minecraft:chalkboard': { texture: 'textures/items/chalkboard_small', type: 'item' },
	'minecraft:charcoal': { texture: 'textures/items/charcoal', type: 'item' },
	'minecraft:cherry_boat': { texture: 'textures/items/cherry_boat', type: 'item' },
	'minecraft:cherry_chest_boat': { texture: 'textures/items/cherry_chest_boat', type: 'item' },
	'minecraft:cherry_door': { texture: 'textures/items/cherry_door', type: 'item' },
	'minecraft:cherry_sign': { texture: 'textures/items/cherry_sign', type: 'item' },
	'minecraft:chest_minecart': { texture: 'textures/items/minecart_chest', type: 'item' },
	'minecraft:chicken': { texture: 'textures/items/chicken_raw', type: 'item' },
	'minecraft:chicken_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_chicken', type: 'item' },
	'minecraft:chorus_fruit': { texture: 'textures/items/chorus_fruit', type: 'item' },
	'minecraft:clay_ball': { texture: 'textures/items/clay_ball', type: 'item' },
	'minecraft:clock': { texture: 'textures/items/clock_item', type: 'item' },
	'minecraft:coal': { texture: 'textures/items/coal', type: 'item' },
	'minecraft:coast_armor_trim_smithing_template': { texture: 'textures/items/coast_armor_trim_smithing_template', type: 'item' },
	'minecraft:cocoa_beans': { texture: 'textures/items/dye_powder_brown', type: 'item' },
	'minecraft:cod': { texture: 'textures/items/fish_raw', type: 'item' },
	'minecraft:cod_bucket': { texture: 'textures/items/bucket_cod', type: 'item' },
	'minecraft:cod_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_cod', type: 'item' },
	'minecraft:command_block_minecart': { texture: 'textures/items/minecart_command_block', type: 'item' },
	'minecraft:comparator': { texture: 'textures/items/comparator', type: 'item' },
	'minecraft:compass': { texture: 'textures/items/compass_item', type: 'item' },
	'minecraft:cooked_beef': { texture: 'textures/items/beef_cooked', type: 'item' },
	'minecraft:cooked_chicken': { texture: 'textures/items/chicken_cooked', type: 'item' },
	'minecraft:cooked_cod': { texture: 'textures/items/fish_cooked', type: 'item' },
	'minecraft:cooked_mutton': { texture: 'textures/items/mutton_cooked', type: 'item' },
	'minecraft:cooked_porkchop': { texture: 'textures/items/porkchop_cooked', type: 'item' },
	'minecraft:cooked_rabbit': { texture: 'textures/items/rabbit_cooked', type: 'item' },
	'minecraft:cooked_salmon': { texture: 'textures/items/fish_salmon_cooked', type: 'item' },
	'minecraft:cookie': { texture: 'textures/items/cookie', type: 'item' },
	'minecraft:copper_axe': { texture: 'textures/items/copper_axe', type: 'item' },
	'minecraft:copper_boots': { texture: 'textures/items/copper_boots', type: 'item' },
	'minecraft:copper_chestplate': { texture: 'textures/items/copper_chestplate', type: 'item' },
	'minecraft:copper_door': { texture: 'textures/items/copper_door', type: 'item' },
	'minecraft:copper_golem_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_copper_golem', type: 'item' },
	'minecraft:copper_helmet': { texture: 'textures/items/copper_helmet', type: 'item' },
	'minecraft:copper_hoe': { texture: 'textures/items/copper_hoe', type: 'item' },
	'minecraft:copper_horse_armor': { texture: 'textures/items/copper_horse_armor', type: 'item' },
	'minecraft:copper_ingot': { texture: 'textures/items/copper_ingot', type: 'item' },
	'minecraft:copper_leggings': { texture: 'textures/items/copper_leggings', type: 'item' },
	'minecraft:copper_nautilus_armor': { texture: 'textures/items/nautilus_armor/copper_nautilus_armor', type: 'item' },
	'minecraft:copper_nugget': { texture: 'textures/items/copper_nugget', type: 'item' },
	'minecraft:copper_pickaxe': { texture: 'textures/items/copper_pickaxe', type: 'item' },
	'minecraft:copper_shovel': { texture: 'textures/items/copper_shovel', type: 'item' },
	'minecraft:copper_spear': { texture: 'textures/items/spear/copper_spear', type: 'item' },
	'minecraft:copper_sword': { texture: 'textures/items/copper_sword', type: 'item' },
	'minecraft:cow_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_cow', type: 'item' },
	'minecraft:creaking_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_creaking', type: 'item' },
	'minecraft:creeper_banner_pattern': { texture: 'textures/items/creeper_banner_pattern', type: 'item' },
	'minecraft:creeper_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_creeper', type: 'item' },
	'minecraft:crimson_door': { texture: 'textures/items/crimson_door', type: 'item' },
	'minecraft:crimson_sign': { texture: 'textures/items/sign_crimson', type: 'item' },
	'minecraft:crossbow': { texture: 'textures/items/crossbow_standby', type: 'item' },
	'minecraft:cyan_dye': { texture: 'textures/items/dye_powder_cyan', type: 'item' },
	'minecraft:danger_pottery_sherd': { texture: 'textures/items/danger_pottery_sherd', type: 'item' },
	'minecraft:dark_oak_chest_boat': { texture: 'textures/items/dark_oak_chest_boat', type: 'item' },
	'minecraft:dark_oak_door': { texture: 'textures/items/door_dark_oak', type: 'item' },
	'minecraft:decay_arrow': { texture: 'textures/items/tipped_arrow_wither', type: 'item' },
	'minecraft:decay_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_wither', type: 'item' },
	'minecraft:decay_potion': { texture: 'textures/items/potion_bottle_wither', type: 'item' },
	'minecraft:decay_splash_potion': { texture: 'textures/items/potion_bottle_splash_wither', type: 'item' },
	'minecraft:diamond': { texture: 'textures/items/diamond', type: 'item' },
	'minecraft:diamond_axe': { texture: 'textures/items/diamond_axe', type: 'item' },
	'minecraft:diamond_boots': { texture: 'textures/items/diamond_boots', type: 'item' },
	'minecraft:diamond_chestplate': { texture: 'textures/items/diamond_chestplate', type: 'item' },
	'minecraft:diamond_helmet': { texture: 'textures/items/diamond_helmet', type: 'item' },
	'minecraft:diamond_hoe': { texture: 'textures/items/diamond_hoe', type: 'item' },
	'minecraft:diamond_horse_armor': { texture: 'textures/items/diamond_horse_armor', type: 'item' },
	'minecraft:diamond_leggings': { texture: 'textures/items/diamond_leggings', type: 'item' },
	'minecraft:diamond_nautilus_armor': { texture: 'textures/items/nautilus_armor/diamond_nautilus_armor', type: 'item' },
	'minecraft:diamond_pickaxe': { texture: 'textures/items/diamond_pickaxe', type: 'item' },
	'minecraft:diamond_shovel': { texture: 'textures/items/diamond_shovel', type: 'item' },
	'minecraft:diamond_spear': { texture: 'textures/items/spear/diamond_spear', type: 'item' },
	'minecraft:diamond_sword': { texture: 'textures/items/diamond_sword', type: 'item' },
	'minecraft:disc_fragment_5': { texture: 'textures/items/disc_fragment_5', type: 'item' },
	'minecraft:dolphin_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_dolphin', type: 'item' },
	'minecraft:donkey_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_donkey', type: 'item' },
	'minecraft:dragon_breath': { texture: 'textures/items/dragons_breath', type: 'item' },
	'minecraft:dried_kelp': { texture: 'textures/items/dried_kelp', type: 'item' },
	'minecraft:drowned_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_drowned', type: 'item' },
	'minecraft:dune_armor_trim_smithing_template': { texture: 'textures/items/dune_armor_trim_smithing_template', type: 'item' },
	'minecraft:echo_shard': { texture: 'textures/items/echo_shard', type: 'item' },
	'minecraft:egg': { texture: 'textures/items/egg', type: 'item' },
	'minecraft:elder_guardian_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_elder_guardian', type: 'item' },
	'minecraft:elytra': { texture: 'textures/items/elytra', type: 'item' },
	'minecraft:emerald': { texture: 'textures/items/emerald', type: 'item' },
	'minecraft:empty_map': { texture: 'textures/items/map_empty', type: 'item' },
	'minecraft:enchanted_book': { texture: 'textures/items/book_enchanted', type: 'item' },
	'minecraft:enchanted_golden_apple': { texture: 'textures/items/apple_golden', type: 'item' },
	'minecraft:end_crystal': { texture: 'textures/items/end_crystal', type: 'item' },
	'minecraft:ender_dragon_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_ender_dragon', type: 'item' },
	'minecraft:ender_eye': { texture: 'textures/items/ender_eye', type: 'item' },
	'minecraft:ender_pearl': { texture: 'textures/items/ender_pearl', type: 'item' },
	'minecraft:enderman_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_enderman', type: 'item' },
	'minecraft:endermite_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_endermite', type: 'item' },
	'minecraft:evoker_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_evoker', type: 'item' },
	'minecraft:experience_bottle': { texture: 'textures/items/experience_bottle', type: 'item' },
	'minecraft:explorer_pottery_sherd': { texture: 'textures/items/explorer_pottery_sherd', type: 'item' },
	'minecraft:exposed_copper_door': { texture: 'textures/items/exposed_copper_door', type: 'item' },
	'minecraft:eye_armor_trim_smithing_template': { texture: 'textures/items/eye_armor_trim_smithing_template', type: 'item' },
	'minecraft:feather': { texture: 'textures/items/feather', type: 'item' },
	'minecraft:field_masoned_banner_pattern': { texture: 'textures/items/field_masoned_banner_pattern', type: 'item' },
	'minecraft:filled_map': { texture: 'textures/items/map_filled', type: 'item' },
	'minecraft:fire_charge': { texture: 'textures/items/fireball', type: 'item' },
	'minecraft:fire_resistance_arrow': { texture: 'textures/items/tipped_arrow_fireres', type: 'item' },
	'minecraft:fire_resistance_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_fireResistance', type: 'item' },
	'minecraft:fire_resistance_potion': { texture: 'textures/items/potion_bottle_fireResistance', type: 'item' },
	'minecraft:fire_resistance_splash_potion': { texture: 'textures/items/potion_bottle_splash_fireResistance', type: 'item' },
	'minecraft:firework_rocket': { texture: 'textures/items/fireworks', type: 'item' },
	'minecraft:firework_star': { texture: 'textures/items/fireworks_charge', type: 'item' },
	'minecraft:fishing_rod': { texture: 'textures/items/fishing_rod_uncast', type: 'item' },
	'minecraft:flint': { texture: 'textures/items/flint', type: 'item' },
	'minecraft:flint_and_steel': { texture: 'textures/items/flint_and_steel', type: 'item' },
	'minecraft:flow_armor_trim_smithing_template': { texture: 'textures/items/flow_armor_trim_smithing_template', type: 'item' },
	'minecraft:flow_banner_pattern': { texture: 'textures/items/flow_banner_pattern', type: 'item' },
	'minecraft:flow_pottery_sherd': { texture: 'textures/items/flow_pottery_sherd', type: 'item' },
	'minecraft:flower_banner_pattern': { texture: 'textures/items/flower_banner_pattern', type: 'item' },
	'minecraft:flower_pot': { texture: 'textures/items/flower_pot', type: 'item' },
	'minecraft:fox_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_fox', type: 'item' },
	'minecraft:friend_pottery_sherd': { texture: 'textures/items/friend_pottery_sherd', type: 'item' },
	'minecraft:frog_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_frog', type: 'item' },
	'minecraft:ghast_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_ghast', type: 'item' },
	'minecraft:ghast_tear': { texture: 'textures/items/ghast_tear', type: 'item' },
	'minecraft:glass_bottle': { texture: 'textures/items/potion_bottle_empty', type: 'item' },
	'minecraft:glistering_melon_slice': { texture: 'textures/items/melon_speckled', type: 'item' },
	'minecraft:globe_banner_pattern': { texture: 'textures/items/globe_banner_pattern', type: 'item' },
	'minecraft:glow_berries': { texture: 'textures/items/glow_berries', type: 'item' },
	'minecraft:glow_ink_sac': { texture: 'textures/items/dye_powder_glow', type: 'item' },
	'minecraft:glow_squid_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_glow_squid', type: 'item' },
	'minecraft:glowstone_dust': { texture: 'textures/items/glowstone_dust', type: 'item' },
	'minecraft:goat_horn': { texture: 'textures/items/goat_horn', type: 'item' },
	'minecraft:goat_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_goat', type: 'item' },
	'minecraft:gold_ingot': { texture: 'textures/items/gold_ingot', type: 'item' },
	'minecraft:gold_nugget': { texture: 'textures/items/gold_nugget', type: 'item' },
	'minecraft:golden_axe': { texture: 'textures/items/gold_axe', type: 'item' },
	'minecraft:golden_boots': { texture: 'textures/items/gold_boots', type: 'item' },
	'minecraft:golden_chestplate': { texture: 'textures/items/gold_chestplate', type: 'item' },
	'minecraft:golden_helmet': { texture: 'textures/items/gold_helmet', type: 'item' },
	'minecraft:golden_hoe': { texture: 'textures/items/gold_hoe', type: 'item' },
	'minecraft:golden_horse_armor': { texture: 'textures/items/gold_horse_armor', type: 'item' },
	'minecraft:golden_leggings': { texture: 'textures/items/gold_leggings', type: 'item' },
	'minecraft:golden_nautilus_armor': { texture: 'textures/items/nautilus_armor/gold_nautilus_armor', type: 'item' },
	'minecraft:golden_pickaxe': { texture: 'textures/items/gold_pickaxe', type: 'item' },
	'minecraft:golden_shovel': { texture: 'textures/items/gold_shovel', type: 'item' },
	'minecraft:golden_spear': { texture: 'textures/items/spear/gold_spear', type: 'item' },
	'minecraft:golden_sword': { texture: 'textures/items/gold_sword', type: 'item' },
	'minecraft:gray_dye': { texture: 'textures/items/dye_powder_gray', type: 'item' },
	'minecraft:green_dye': { texture: 'textures/items/dye_powder_green', type: 'item' },
	'minecraft:guardian_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_guardian', type: 'item' },
	'minecraft:gunpowder': { texture: 'textures/items/gunpowder', type: 'item' },
	'minecraft:guster_banner_pattern': { texture: 'textures/items/guster_banner_pattern', type: 'item' },
	'minecraft:guster_pottery_sherd': { texture: 'textures/items/guster_pottery_sherd', type: 'item' },
	'minecraft:hanging_roots': { texture: 'textures/items/hanging_roots', type: 'item' },
	'minecraft:happy_ghast_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_happy_ghast', type: 'item' },
	'minecraft:harming_arrow': { texture: 'textures/items/tipped_arrow_harm', type: 'item' },
	'minecraft:harming_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_harm', type: 'item' },
	'minecraft:harming_potion': { texture: 'textures/items/potion_bottle_harm', type: 'item' },
	'minecraft:harming_splash_potion': { texture: 'textures/items/potion_bottle_splash_harm', type: 'item' },
	'minecraft:healing_arrow': { texture: 'textures/items/tipped_arrow_healing', type: 'item' },
	'minecraft:healing_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_heal', type: 'item' },
	'minecraft:healing_potion': { texture: 'textures/items/potion_bottle_heal', type: 'item' },
	'minecraft:healing_splash_potion': { texture: 'textures/items/potion_bottle_splash_heal', type: 'item' },
	'minecraft:heart_of_the_sea': { texture: 'textures/items/heartofthesea_closed', type: 'item' },
	'minecraft:heart_pottery_sherd': { texture: 'textures/items/heart_pottery_sherd', type: 'item' },
	'minecraft:heartbreak_pottery_sherd': { texture: 'textures/items/heartbreak_pottery_sherd', type: 'item' },
	'minecraft:hoglin_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_hoglin', type: 'item' },
	'minecraft:honey_bottle': { texture: 'textures/items/honey_bottle', type: 'item' },
	'minecraft:honeycomb': { texture: 'textures/items/honeycomb', type: 'item' },
	'minecraft:hopper': { texture: 'textures/items/hopper', type: 'item' },
	'minecraft:hopper_minecart': { texture: 'textures/items/minecart_hopper', type: 'item' },
	'minecraft:horse_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_horse', type: 'item' },
	'minecraft:host_armor_trim_smithing_template': { texture: 'textures/items/host_armor_trim_smithing_template', type: 'item' },
	'minecraft:howl_pottery_sherd': { texture: 'textures/items/howl_pottery_sherd', type: 'item' },
	'minecraft:husk_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_husk', type: 'item' },
	'minecraft:ink_sac': { texture: 'textures/items/dye_powder_black', type: 'item' },
	'minecraft:iron_axe': { texture: 'textures/items/iron_axe', type: 'item' },
	'minecraft:iron_boots': { texture: 'textures/items/iron_boots', type: 'item' },
	'minecraft:iron_chestplate': { texture: 'textures/items/iron_chestplate', type: 'item' },
	'minecraft:iron_door': { texture: 'textures/items/door_iron', type: 'item' },
	'minecraft:iron_golem_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_iron_golem', type: 'item' },
	'minecraft:iron_helmet': { texture: 'textures/items/iron_helmet', type: 'item' },
	'minecraft:iron_hoe': { texture: 'textures/items/iron_hoe', type: 'item' },
	'minecraft:iron_horse_armor': { texture: 'textures/items/iron_horse_armor', type: 'item' },
	'minecraft:iron_ingot': { texture: 'textures/items/iron_ingot', type: 'item' },
	'minecraft:iron_leggings': { texture: 'textures/items/iron_leggings', type: 'item' },
	'minecraft:iron_nautilus_armor': { texture: 'textures/items/nautilus_armor/iron_nautilus_armor', type: 'item' },
	'minecraft:iron_nugget': { texture: 'textures/items/iron_nugget', type: 'item' },
	'minecraft:iron_pickaxe': { texture: 'textures/items/iron_pickaxe', type: 'item' },
	'minecraft:iron_shovel': { texture: 'textures/items/iron_shovel', type: 'item' },
	'minecraft:iron_spear': { texture: 'textures/items/spear/iron_spear', type: 'item' },
	'minecraft:iron_sword': { texture: 'textures/items/iron_sword', type: 'item' },
	'minecraft:jungle_boat': { texture: 'textures/items/boat_jungle', type: 'item' },
	'minecraft:jungle_chest_boat': { texture: 'textures/items/jungle_chest_boat', type: 'item' },
	'minecraft:jungle_door': { texture: 'textures/items/door_jungle', type: 'item' },
	'minecraft:jungle_sign': { texture: 'textures/items/sign_jungle', type: 'item' },
	'minecraft:kelp': { texture: 'textures/items/kelp', type: 'item' },
	'minecraft:lapis_lazuli': { texture: 'textures/items/dye_powder_blue', type: 'item' },
	'minecraft:lava_bucket': { texture: 'textures/items/bucket_lava', type: 'item' },
	'minecraft:lead': { texture: 'textures/items/lead', type: 'item' },
	'minecraft:leaping_arrow': { texture: 'textures/items/tipped_arrow_leaping', type: 'item' },
	'minecraft:leaping_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_jump', type: 'item' },
	'minecraft:leaping_potion': { texture: 'textures/items/potion_bottle_jump', type: 'item' },
	'minecraft:leaping_splash_potion': { texture: 'textures/items/potion_bottle_splash_jump', type: 'item' },
	'minecraft:leather': { texture: 'textures/items/leather', type: 'item' },
	'minecraft:leather_boots': { texture: 'textures/items/leather_boots', type: 'item' },
	'minecraft:leather_chestplate': { texture: 'textures/items/leather_chestplate', type: 'item' },
	'minecraft:leather_helmet': { texture: 'textures/items/leather_helmet', type: 'item' },
	'minecraft:leather_horse_armor': { texture: 'textures/items/leather_horse_armor', type: 'item' },
	'minecraft:leather_leggings': { texture: 'textures/items/leather_leggings', type: 'item' },
	'minecraft:lever': { texture: 'textures/items/lever', type: 'item' },
	'minecraft:light_blue_dye': { texture: 'textures/items/dye_powder_light_blue', type: 'item' },
	'minecraft:light_gray_dye': { texture: 'textures/items/dye_powder_silver', type: 'item' },
	'minecraft:lime_dye': { texture: 'textures/items/dye_powder_lime', type: 'item' },
	'minecraft:llama_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_llama', type: 'item' },
	'minecraft:lodestone_compass': { texture: 'textures/items/lodestonecompass_item', type: 'item' },
	'minecraft:mace': { texture: 'textures/items/mace', type: 'item' },
	'minecraft:magenta_dye': { texture: 'textures/items/dye_powder_magenta', type: 'item' },
	'minecraft:magma_cream': { texture: 'textures/items/magma_cream', type: 'item' },
	'minecraft:magma_cube_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_magma_cube', type: 'item' },
	'minecraft:mangrove_boat': { texture: 'textures/items/mangrove_boat', type: 'item' },
	'minecraft:mangrove_chest_boat': { texture: 'textures/items/mangrove_chest_boat', type: 'item' },
	'minecraft:mangrove_door': { texture: 'textures/items/mangrove_door', type: 'item' },
	'minecraft:mangrove_sign': { texture: 'textures/items/mangrove_sign', type: 'item' },
	'minecraft:melon_seeds': { texture: 'textures/items/seeds_melon', type: 'item' },
	'minecraft:melon_slice': { texture: 'textures/items/melon', type: 'item' },
	'minecraft:milk_bucket': { texture: 'textures/items/bucket_milk', type: 'item' },
	'minecraft:miner_pottery_sherd': { texture: 'textures/items/miner_pottery_sherd', type: 'item' },
	'minecraft:mojang_banner_pattern': { texture: 'textures/items/mojang_banner_pattern', type: 'item' },
	'minecraft:mooshroom_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_mooshroom', type: 'item' },
	'minecraft:mourner_pottery_sherd': { texture: 'textures/items/mourner_pottery_sherd', type: 'item' },
	'minecraft:mule_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_mule', type: 'item' },
	'minecraft:mundane_arrow': { texture: 'textures/items/tipped_arrow', type: 'item' },
	'minecraft:mundane_lingering_potion': { texture: 'textures/items/potion_bottle_lingering', type: 'item' },
	'minecraft:mundane_potion': { texture: 'textures/items/potion_bottle_drinkable', type: 'item' },
	'minecraft:mundane_splash_potion': { texture: 'textures/items/potion_bottle_splash', type: 'item' },
	'minecraft:mushroom_stew': { texture: 'textures/items/mushroom_stew', type: 'item' },
	'minecraft:music_disc_11': { texture: 'textures/items/record_11', type: 'item' },
	'minecraft:music_disc_13': { texture: 'textures/items/record_13', type: 'item' },
	'minecraft:music_disc_5': { texture: 'textures/items/record_5', type: 'item' },
	'minecraft:music_disc_blocks': { texture: 'textures/items/record_blocks', type: 'item' },
	'minecraft:music_disc_bounce': { texture: 'textures/items/music_disc_bounce', type: 'item' },
	'minecraft:music_disc_cat': { texture: 'textures/items/record_cat', type: 'item' },
	'minecraft:music_disc_chirp': { texture: 'textures/items/record_chirp', type: 'item' },
	'minecraft:music_disc_creator': { texture: 'textures/items/music_disc_creator', type: 'item' },
	'minecraft:music_disc_creator_music_box': { texture: 'textures/items/music_disc_creator_music_box', type: 'item' },
	'minecraft:music_disc_far': { texture: 'textures/items/record_far', type: 'item' },
	'minecraft:music_disc_lava_chicken': { texture: 'textures/items/music_disc_lava_chicken', type: 'item' },
	'minecraft:music_disc_mall': { texture: 'textures/items/record_mall', type: 'item' },
	'minecraft:music_disc_mellohi': { texture: 'textures/items/record_mellohi', type: 'item' },
	'minecraft:music_disc_otherside': { texture: 'textures/items/record_otherside', type: 'item' },
	'minecraft:music_disc_pigstep': { texture: 'textures/items/record_pigstep', type: 'item' },
	'minecraft:music_disc_precipice': { texture: 'textures/items/music_disc_precipice', type: 'item' },
	'minecraft:music_disc_relic': { texture: 'textures/items/music_disc_relic', type: 'item' },
	'minecraft:music_disc_stal': { texture: 'textures/items/record_stal', type: 'item' },
	'minecraft:music_disc_strad': { texture: 'textures/items/record_strad', type: 'item' },
	'minecraft:music_disc_tears': { texture: 'textures/items/music_disc_tears', type: 'item' },
	'minecraft:music_disc_wait': { texture: 'textures/items/record_wait', type: 'item' },
	'minecraft:music_disc_ward': { texture: 'textures/items/record_ward', type: 'item' },
	'minecraft:mutton': { texture: 'textures/items/mutton_raw', type: 'item' },
	'minecraft:name_tag': { texture: 'textures/items/name_tag', type: 'item' },
	'minecraft:nautilus_shell': { texture: 'textures/items/nautilus', type: 'item' },
	'minecraft:nautilus_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_nautilus', type: 'item' },
	'minecraft:nether_sprouts': { texture: 'textures/items/nether_sprouts', type: 'item' },
	'minecraft:nether_star': { texture: 'textures/items/nether_star', type: 'item' },
	'minecraft:nether_wart': { texture: 'textures/items/nether_wart', type: 'item' },
	'minecraft:netherbrick': { texture: 'textures/items/netherbrick', type: 'item' },
	'minecraft:netherite_axe': { texture: 'textures/items/netherite_axe', type: 'item' },
	'minecraft:netherite_boots': { texture: 'textures/items/netherite_boots', type: 'item' },
	'minecraft:netherite_chestplate': { texture: 'textures/items/netherite_chestplate', type: 'item' },
	'minecraft:netherite_helmet': { texture: 'textures/items/netherite_helmet', type: 'item' },
	'minecraft:netherite_hoe': { texture: 'textures/items/netherite_hoe', type: 'item' },
	'minecraft:netherite_horse_armor': { texture: 'textures/items/netherite_horse_armor', type: 'item' },
	'minecraft:netherite_ingot': { texture: 'textures/items/netherite_ingot', type: 'item' },
	'minecraft:netherite_leggings': { texture: 'textures/items/netherite_leggings', type: 'item' },
	'minecraft:netherite_nautilus_armor': { texture: 'textures/items/nautilus_armor/netherite_nautilus_armor', type: 'item' },
	'minecraft:netherite_pickaxe': { texture: 'textures/items/netherite_pickaxe', type: 'item' },
	'minecraft:netherite_scrap': { texture: 'textures/items/netherite_scrap', type: 'item' },
	'minecraft:netherite_shovel': { texture: 'textures/items/netherite_shovel', type: 'item' },
	'minecraft:netherite_spear': { texture: 'textures/items/spear/netherite_spear', type: 'item' },
	'minecraft:netherite_sword': { texture: 'textures/items/netherite_sword', type: 'item' },
	'minecraft:netherite_upgrade_smithing_template': { texture: 'textures/items/netherite_upgrade_smithing_template', type: 'item' },
	'minecraft:night_vision_arrow': { texture: 'textures/items/tipped_arrow_nightvision', type: 'item' },
	'minecraft:night_vision_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_nightVision', type: 'item' },
	'minecraft:night_vision_potion': { texture: 'textures/items/potion_bottle_nightVision', type: 'item' },
	'minecraft:night_vision_splash_potion': { texture: 'textures/items/potion_bottle_splash_nightVision', type: 'item' },
	'minecraft:oak_boat': { texture: 'textures/items/boat_oak', type: 'item' },
	'minecraft:oak_chest_boat': { texture: 'textures/items/oak_chest_boat', type: 'item' },
	'minecraft:ocelot_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_ocelot', type: 'item' },
	'minecraft:ominous_bottle': { texture: 'textures/items/ominous_bottle', type: 'item' },
	'minecraft:ominous_trial_key': { texture: 'textures/items/ominous_trial_key', type: 'item' },
	'minecraft:orange_dye': { texture: 'textures/items/dye_powder_orange', type: 'item' },
	'minecraft:oxidized_copper_door': { texture: 'textures/items/oxidized_copper_door', type: 'item' },
	'minecraft:painting': { texture: 'textures/items/painting', type: 'item' },
	'minecraft:pale_oak_boat': { texture: 'textures/items/pale_oak_boat', type: 'item' },
	'minecraft:pale_oak_chest_boat': { texture: 'textures/items/pale_oak_chest_boat', type: 'item' },
	'minecraft:pale_oak_door': { texture: 'textures/items/pale_oak_door', type: 'item' },
	'minecraft:pale_oak_sign': { texture: 'textures/items/pale_oak_sign', type: 'item' },
	'minecraft:panda_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_panda', type: 'item' },
	'minecraft:paper': { texture: 'textures/items/paper', type: 'item' },
	'minecraft:parched_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_parched', type: 'item' },
	'minecraft:parrot_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_parrot', type: 'item' },
	'minecraft:phantom_membrane': { texture: 'textures/items/phantom_membrane', type: 'item' },
	'minecraft:phantom_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_phantom', type: 'item' },
	'minecraft:pig_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_pig', type: 'item' },
	'minecraft:piglin_banner_pattern': { texture: 'textures/items/piglin_banner_pattern', type: 'item' },
	'minecraft:piglin_brute_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_piglin_brute', type: 'item' },
	'minecraft:piglin_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_piglin', type: 'item' },
	'minecraft:pillager_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_pillager', type: 'item' },
	'minecraft:pink_dye': { texture: 'textures/items/dye_powder_pink', type: 'item' },
	'minecraft:pitcher_pod': { texture: 'textures/items/pitcher_pod', type: 'item' },
	'minecraft:plenty_pottery_sherd': { texture: 'textures/items/plenty_pottery_sherd', type: 'item' },
	'minecraft:poison_arrow': { texture: 'textures/items/tipped_arrow_poison', type: 'item' },
	'minecraft:poison_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_poison', type: 'item' },
	'minecraft:poison_potion': { texture: 'textures/items/potion_bottle_poison', type: 'item' },
	'minecraft:poison_splash_potion': { texture: 'textures/items/potion_bottle_splash_poison', type: 'item' },
	'minecraft:polar_bear_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_polar_bear', type: 'item' },
	'minecraft:porkchop': { texture: 'textures/items/porkchop_raw', type: 'item' },
	'minecraft:potato': { texture: 'textures/items/potato', type: 'item' },
	'minecraft:powder_snow_bucket': { texture: 'textures/items/bucket_powder_snow', type: 'item' },
	'minecraft:prismarine_crystals': { texture: 'textures/items/prismarine_crystals', type: 'item' },
	'minecraft:prismarine_shard': { texture: 'textures/items/prismarine_shard', type: 'item' },
	'minecraft:prize_pottery_sherd': { texture: 'textures/items/prize_pottery_sherd', type: 'item' },
	'minecraft:pufferfish': { texture: 'textures/items/fish_pufferfish_raw', type: 'item' },
	'minecraft:pufferfish_bucket': { texture: 'textures/items/bucket_pufferfish', type: 'item' },
	'minecraft:pufferfish_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_pufferfish', type: 'item' },
	'minecraft:pumpkin_pie': { texture: 'textures/items/pumpkin_pie', type: 'item' },
	'minecraft:pumpkin_seeds': { texture: 'textures/items/seeds_pumpkin', type: 'item' },
	'minecraft:purple_dye': { texture: 'textures/items/dye_powder_purple', type: 'item' },
	'minecraft:quartz': { texture: 'textures/items/quartz', type: 'item' },
	'minecraft:rabbit': { texture: 'textures/items/rabbit_raw', type: 'item' },
	'minecraft:rabbit_foot': { texture: 'textures/items/rabbit_foot', type: 'item' },
	'minecraft:rabbit_hide': { texture: 'textures/items/rabbit_hide', type: 'item' },
	'minecraft:rabbit_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_rabbit', type: 'item' },
	'minecraft:rabbit_stew': { texture: 'textures/items/rabbit_stew', type: 'item' },
	'minecraft:raiser_armor_trim_smithing_template': { texture: 'textures/items/raiser_armor_trim_smithing_template', type: 'item' },
	'minecraft:ravager_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_ravager', type: 'item' },
	'minecraft:raw_copper': { texture: 'textures/items/raw_copper', type: 'item' },
	'minecraft:raw_gold': { texture: 'textures/items/raw_gold', type: 'item' },
	'minecraft:raw_iron': { texture: 'textures/items/raw_iron', type: 'item' },
	'minecraft:recovery_compass': { texture: 'textures/items/recovery_compass_item', type: 'item' },
	'minecraft:red_dye': { texture: 'textures/items/dye_powder_red', type: 'item' },
	'minecraft:reeds': { texture: 'textures/items/reeds', type: 'item' },
	'minecraft:regeneration_arrow': { texture: 'textures/items/tipped_arrow_regen', type: 'item' },
	'minecraft:regeneration_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_regeneration', type: 'item' },
	'minecraft:regeneration_potion': { texture: 'textures/items/potion_bottle_regeneration', type: 'item' },
	'minecraft:regeneration_splash_potion': { texture: 'textures/items/potion_bottle_splash_regeneration', type: 'item' },
	'minecraft:repeater': { texture: 'textures/items/repeater', type: 'item' },
	'minecraft:resin_brick': { texture: 'textures/items/resin_brick', type: 'item' },
	'minecraft:rib_armor_trim_smithing_template': { texture: 'textures/items/rib_armor_trim_smithing_template', type: 'item' },
	'minecraft:rotten_flesh': { texture: 'textures/items/rotten_flesh', type: 'item' },
	'minecraft:saddle': { texture: 'textures/items/saddle', type: 'item' },
	'minecraft:salmon': { texture: 'textures/items/fish_salmon_raw', type: 'item' },
	'minecraft:salmon_bucket': { texture: 'textures/items/bucket_salmon', type: 'item' },
	'minecraft:salmon_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_salmon', type: 'item' },
	'minecraft:scrape_pottery_sherd': { texture: 'textures/items/scrape_pottery_sherd', type: 'item' },
	'minecraft:sentry_armor_trim_smithing_template': { texture: 'textures/items/sentry_armor_trim_smithing_template', type: 'item' },
	'minecraft:shaper_armor_trim_smithing_template': { texture: 'textures/items/shaper_armor_trim_smithing_template', type: 'item' },
	'minecraft:sheaf_pottery_sherd': { texture: 'textures/items/sheaf_pottery_sherd', type: 'item' },
	'minecraft:shears': { texture: 'textures/items/shears', type: 'item' },
	'minecraft:sheep_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_sheep', type: 'item' },
	'minecraft:shelter_pottery_sherd': { texture: 'textures/items/shelter_pottery_sherd', type: 'item' },
	'minecraft:shield': { texture: 'textures/entity/shield', type: 'item' },
	'minecraft:shulker_shell': { texture: 'textures/items/shulker_shell', type: 'item' },
	'minecraft:shulker_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_shulker', type: 'item' },
	'minecraft:silence_armor_trim_smithing_template': { texture: 'textures/items/silence_armor_trim_smithing_template', type: 'item' },
	'minecraft:silverfish_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_silverfish', type: 'item' },
	'minecraft:skeleton_horse_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_skeleton_horse', type: 'item' },
	'minecraft:skeleton_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_skeleton', type: 'item' },
	'minecraft:skull_banner_pattern': { texture: 'textures/items/skull_banner_pattern', type: 'item' },
	'minecraft:skull_pottery_sherd': { texture: 'textures/items/skull_pottery_sherd', type: 'item' },
	'minecraft:slime_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_slime', type: 'item' },
	'minecraft:slow_falling_arrow': { texture: 'textures/items/tipped_arrow_slowfalling', type: 'item' },
	'minecraft:slow_falling_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_slowFall', type: 'item' },
	'minecraft:slow_falling_potion': { texture: 'textures/items/potion_bottle_slowFall', type: 'item' },
	'minecraft:slow_falling_splash_potion': { texture: 'textures/items/potion_bottle_splash_slowFall', type: 'item' },
	'minecraft:slowness_arrow': { texture: 'textures/items/tipped_arrow_slow', type: 'item' },
	'minecraft:slowness_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_moveSlowdown', type: 'item' },
	'minecraft:slowness_potion': { texture: 'textures/items/potion_bottle_moveSlowdown', type: 'item' },
	'minecraft:slowness_splash_potion': { texture: 'textures/items/potion_bottle_splash_moveSlowdown', type: 'item' },
	'minecraft:sniffer_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_sniffer', type: 'item' },
	'minecraft:snort_pottery_sherd': { texture: 'textures/items/snort_pottery_sherd', type: 'item' },
	'minecraft:snout_armor_trim_smithing_template': { texture: 'textures/items/snout_armor_trim_smithing_template', type: 'item' },
	'minecraft:snow_golem_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_snow_golem', type: 'item' },
	'minecraft:snowball': { texture: 'textures/items/snowball', type: 'item' },
	'minecraft:soul_campfire': { texture: 'textures/items/soul_campfire', type: 'item' },
	'minecraft:spawn_egg': { texture: 'textures/items/egg_chicken', type: 'item' },
	'minecraft:spider_eye': { texture: 'textures/items/spider_eye', type: 'item' },
	'minecraft:spider_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_spider', type: 'item' },
	'minecraft:spire_armor_trim_smithing_template': { texture: 'textures/items/spire_armor_trim_smithing_template', type: 'item' },
	'minecraft:splash_arrow': { texture: 'textures/items/tipped_arrow', type: 'item' },
	'minecraft:spruce_boat': { texture: 'textures/items/boat_spruce', type: 'item' },
	'minecraft:spruce_chest_boat': { texture: 'textures/items/spruce_chest_boat', type: 'item' },
	'minecraft:spruce_door': { texture: 'textures/items/door_spruce', type: 'item' },
	'minecraft:spruce_sign': { texture: 'textures/items/sign_spruce', type: 'item' },
	'minecraft:spyglass': { texture: 'textures/items/spyglass', type: 'item' },
	'minecraft:squid_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_squid', type: 'item' },
	'minecraft:stick': { texture: 'textures/items/stick', type: 'item' },
	'minecraft:stone_axe': { texture: 'textures/items/stone_axe', type: 'item' },
	'minecraft:stone_hoe': { texture: 'textures/items/stone_hoe', type: 'item' },
	'minecraft:stone_pickaxe': { texture: 'textures/items/stone_pickaxe', type: 'item' },
	'minecraft:stone_shovel': { texture: 'textures/items/stone_shovel', type: 'item' },
	'minecraft:stone_spear': { texture: 'textures/items/spear/stone_spear', type: 'item' },
	'minecraft:stone_sword': { texture: 'textures/items/stone_sword', type: 'item' },
	'minecraft:stray_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_stray', type: 'item' },
	'minecraft:strength_arrow': { texture: 'textures/items/tipped_arrow_strength', type: 'item' },
	'minecraft:strength_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_damageBoost', type: 'item' },
	'minecraft:strength_potion': { texture: 'textures/items/potion_bottle_damageBoost', type: 'item' },
	'minecraft:strength_splash_potion': { texture: 'textures/items/potion_bottle_splash_damageBoost', type: 'item' },
	'minecraft:strider_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_strider', type: 'item' },
	'minecraft:string': { texture: 'textures/items/string', type: 'item' },
	'minecraft:sugar': { texture: 'textures/items/sugar', type: 'item' },
	'minecraft:sugar_cane': { texture: 'textures/items/reeds', type: 'item' },
	'minecraft:sulfur_cube_bucket': { texture: 'textures/items/bucket_sulfur_cube', type: 'item' },
	'minecraft:sulfur_cube_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_sulfur_cube', type: 'item' },
	'minecraft:suspicious_stew': { texture: 'textures/items/suspicious_stew', type: 'item' },
	'minecraft:sweet_berries': { texture: 'textures/items/sweet_berries', type: 'item' },
	'minecraft:swiftness_arrow': { texture: 'textures/items/tipped_arrow_swift', type: 'item' },
	'minecraft:swiftness_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_moveSpeed', type: 'item' },
	'minecraft:swiftness_potion': { texture: 'textures/items/potion_bottle_moveSpeed', type: 'item' },
	'minecraft:swiftness_splash_potion': { texture: 'textures/items/potion_bottle_splash_moveSpeed', type: 'item' },
	'minecraft:tadpole_bucket': { texture: 'textures/items/bucket_tadpole', type: 'item' },
	'minecraft:tadpole_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_tadpole', type: 'item' },
	'minecraft:thick_arrow': { texture: 'textures/items/tipped_arrow', type: 'item' },
	'minecraft:thick_lingering_potion': { texture: 'textures/items/potion_bottle_lingering', type: 'item' },
	'minecraft:thick_potion': { texture: 'textures/items/potion_bottle_drinkable', type: 'item' },
	'minecraft:thick_splash_potion': { texture: 'textures/items/potion_bottle_splash', type: 'item' },
	'minecraft:tide_armor_trim_smithing_template': { texture: 'textures/items/tide_armor_trim_smithing_template', type: 'item' },
	'minecraft:tnt_minecart': { texture: 'textures/items/minecart_tnt', type: 'item' },
	'minecraft:torchflower_seeds': { texture: 'textures/items/torchflower_seeds', type: 'item' },
	'minecraft:totem_of_undying': { texture: 'textures/items/totem', type: 'item' },
	'minecraft:trader_llama_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_trader_llama', type: 'item' },
	'minecraft:trial_key': { texture: 'textures/items/trial_key', type: 'item' },
	'minecraft:trident': { texture: 'textures/items/trident', type: 'item' },
	'minecraft:tropical_fish_bucket': { texture: 'textures/items/bucket_tropical', type: 'item' },
	'minecraft:tropical_fish_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_tropicalfish', type: 'item' },
	'minecraft:turtle_helmet': { texture: 'textures/items/turtle_helmet', type: 'item' },
	'minecraft:turtle_master_arrow': { texture: 'textures/items/tipped_arrow_turtlemaster', type: 'item' },
	'minecraft:turtle_master_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_turtleMaster', type: 'item' },
	'minecraft:turtle_master_potion': { texture: 'textures/items/potion_bottle_turtleMaster', type: 'item' },
	'minecraft:turtle_master_splash_potion': { texture: 'textures/items/potion_bottle_splash_turtleMaster', type: 'item' },
	'minecraft:turtle_scute': { texture: 'textures/items/turtle_shell_piece', type: 'item' },
	'minecraft:turtle_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_turtle', type: 'item' },
	'minecraft:vex_armor_trim_smithing_template': { texture: 'textures/items/vex_armor_trim_smithing_template', type: 'item' },
	'minecraft:vex_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_vex', type: 'item' },
	'minecraft:villager_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_villager', type: 'item' },
	'minecraft:vindicator_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_vindicator', type: 'item' },
	'minecraft:wandering_trader_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_wandering_trader', type: 'item' },
	'minecraft:ward_armor_trim_smithing_template': { texture: 'textures/items/ward_armor_trim_smithing_template', type: 'item' },
	'minecraft:warden_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_warden', type: 'item' },
	'minecraft:warped_door': { texture: 'textures/items/warped_door', type: 'item' },
	'minecraft:warped_fungus_on_a_stick': { texture: 'textures/items/warped_fungus_on_a_stick', type: 'item' },
	'minecraft:warped_sign': { texture: 'textures/items/sign_warped', type: 'item' },
	'minecraft:water_breathing_arrow': { texture: 'textures/items/tipped_arrow_waterbreathing', type: 'item' },
	'minecraft:water_breathing_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_waterBreathing', type: 'item' },
	'minecraft:water_breathing_potion': { texture: 'textures/items/potion_bottle_waterBreathing', type: 'item' },
	'minecraft:water_breathing_splash_potion': { texture: 'textures/items/potion_bottle_splash_waterBreathing', type: 'item' },
	'minecraft:water_bucket': { texture: 'textures/items/bucket_water', type: 'item' },
	'minecraft:wayfinder_armor_trim_smithing_template': { texture: 'textures/items/wayfinder_armor_trim_smithing_template', type: 'item' },
	'minecraft:weakness_arrow': { texture: 'textures/items/tipped_arrow_weakness', type: 'item' },
	'minecraft:weakness_lingering_potion': { texture: 'textures/items/potion_bottle_lingering_weakness', type: 'item' },
	'minecraft:weakness_potion': { texture: 'textures/items/potion_bottle_weakness', type: 'item' },
	'minecraft:weakness_splash_potion': { texture: 'textures/items/potion_bottle_splash_weakness', type: 'item' },
	'minecraft:weathered_copper_door': { texture: 'textures/items/weathered_copper_door', type: 'item' },
	'minecraft:wheat': { texture: 'textures/items/wheat', type: 'item' },
	'minecraft:wheat_seeds': { texture: 'textures/items/seeds_wheat', type: 'item' },
	'minecraft:white_dye': { texture: 'textures/items/dye_powder_white', type: 'item' },
	'minecraft:wild_armor_trim_smithing_template': { texture: 'textures/items/wild_armor_trim_smithing_template', type: 'item' },
	'minecraft:wind_charge': { texture: 'textures/items/wind_charge', type: 'item' },
	'minecraft:witch_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_witch', type: 'item' },
	'minecraft:wither_skeleton_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_wither_skeleton', type: 'item' },
	'minecraft:wither_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_wither', type: 'item' },
	'minecraft:wolf_armor': { texture: 'textures/items/wolf_armor', type: 'item' },
	'minecraft:wolf_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_wolf', type: 'item' },
	'minecraft:wooden_axe': { texture: 'textures/items/wood_axe', type: 'item' },
	'minecraft:wooden_door': { texture: 'textures/items/door_wood', type: 'item' },
	'minecraft:wooden_hoe': { texture: 'textures/items/wood_hoe', type: 'item' },
	'minecraft:wooden_pickaxe': { texture: 'textures/items/wood_pickaxe', type: 'item' },
	'minecraft:wooden_shovel': { texture: 'textures/items/wood_shovel', type: 'item' },
	'minecraft:wooden_spear': { texture: 'textures/items/spear/wood_spear', type: 'item' },
	'minecraft:wooden_sword': { texture: 'textures/items/wood_sword', type: 'item' },
	'minecraft:writable_book': { texture: 'textures/items/book_writable', type: 'item' },
	'minecraft:yellow_dye': { texture: 'textures/items/dye_powder_yellow', type: 'item' },
	'minecraft:zoglin_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_zoglin', type: 'item' },
	'minecraft:zombie_horse_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_zombie_horse', type: 'item' },
	'minecraft:zombie_nautilus_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_zombie_nautilus', type: 'item' },
	'minecraft:zombie_pigman_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_zombified_piglin', type: 'item' },
	'minecraft:zombie_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_zombie', type: 'item' },
	'minecraft:zombie_villager_spawn_egg': { texture: 'textures/items/spawn_eggs/spawn_egg_zombie_villager', type: 'item' },

	// â•â• pinned from the shipped texture files â•â•
	// These have no entry in item_texture.json, so they were resolving through
	// the numeric table and shifting. The png exists in the installed vanilla
	// pack even though nothing indexes it, and the resource pack accepts any
	// path under textures/, so the file's own location is the pin.
	'minecraft:black_bundle': { texture: 'textures/items/bundle_black', type: 'item' },
	'minecraft:black_cushion': { texture: 'textures/items/black_cushion', type: 'item' },
	'minecraft:black_harness': { texture: 'textures/items/harness/harness_black', type: 'item' },
	'minecraft:blue_bundle': { texture: 'textures/items/bundle_blue', type: 'item' },
	'minecraft:blue_cushion': { texture: 'textures/items/blue_cushion', type: 'item' },
	'minecraft:blue_harness': { texture: 'textures/items/harness/harness_blue', type: 'item' },
	'minecraft:brown_bundle': { texture: 'textures/items/bundle_brown', type: 'item' },
	'minecraft:brown_cushion': { texture: 'textures/items/brown_cushion', type: 'item' },
	'minecraft:brown_harness': { texture: 'textures/items/harness/harness_brown', type: 'item' },
	'minecraft:cyan_bundle': { texture: 'textures/items/bundle_cyan', type: 'item' },
	'minecraft:cyan_cushion': { texture: 'textures/items/cyan_cushion', type: 'item' },
	'minecraft:cyan_harness': { texture: 'textures/items/harness/harness_cyan', type: 'item' },
	'minecraft:dark_oak_boat': { texture: 'textures/items/boat_dark_oak', type: 'item' },
	'minecraft:fermented_spider_eye': { texture: 'textures/items/spider_eye_fermented', type: 'item' },
	'minecraft:golden_apple': { texture: 'textures/items/apple_golden', type: 'item' },
	'minecraft:golden_carrot': { texture: 'textures/items/carrot_golden', type: 'item' },
	'minecraft:gray_bundle': { texture: 'textures/items/bundle_gray', type: 'item' },
	'minecraft:gray_cushion': { texture: 'textures/items/gray_cushion', type: 'item' },
	'minecraft:gray_harness': { texture: 'textures/items/harness/harness_gray', type: 'item' },
	'minecraft:green_bundle': { texture: 'textures/items/bundle_green', type: 'item' },
	'minecraft:green_cushion': { texture: 'textures/items/green_cushion', type: 'item' },
	'minecraft:green_harness': { texture: 'textures/items/harness/harness_green', type: 'item' },
	'minecraft:light_blue_bundle': { texture: 'textures/items/bundle_light_blue', type: 'item' },
	'minecraft:light_blue_cushion': { texture: 'textures/items/light_blue_cushion', type: 'item' },
	'minecraft:light_blue_harness': { texture: 'textures/items/harness/harness_light_blue', type: 'item' },
	'minecraft:light_gray_bundle': { texture: 'textures/items/bundle_light_gray', type: 'item' },
	'minecraft:light_gray_cushion': { texture: 'textures/items/light_gray_cushion', type: 'item' },
	'minecraft:light_gray_harness': { texture: 'textures/items/harness/harness_light_gray', type: 'item' },
	'minecraft:lime_bundle': { texture: 'textures/items/bundle_lime', type: 'item' },
	'minecraft:lime_cushion': { texture: 'textures/items/lime_cushion', type: 'item' },
	'minecraft:lime_harness': { texture: 'textures/items/harness/harness_lime', type: 'item' },
	'minecraft:lingering_potion': { texture: 'textures/items/potion_bottle_lingering', type: 'item' },
	'minecraft:magenta_bundle': { texture: 'textures/items/bundle_magenta', type: 'item' },
	'minecraft:magenta_cushion': { texture: 'textures/items/magenta_cushion', type: 'item' },
	'minecraft:magenta_harness': { texture: 'textures/items/harness/harness_magenta', type: 'item' },
	'minecraft:minecart': { texture: 'textures/items/minecart_normal', type: 'item' },
	'minecraft:oak_sign': { texture: 'textures/items/sign', type: 'item' },
	'minecraft:orange_bundle': { texture: 'textures/items/bundle_orange', type: 'item' },
	'minecraft:orange_cushion': { texture: 'textures/items/orange_cushion', type: 'item' },
	'minecraft:orange_harness': { texture: 'textures/items/harness/harness_orange', type: 'item' },
	'minecraft:pink_bundle': { texture: 'textures/items/bundle_pink', type: 'item' },
	'minecraft:pink_cushion': { texture: 'textures/items/pink_cushion', type: 'item' },
	'minecraft:pink_harness': { texture: 'textures/items/harness/harness_pink', type: 'item' },
	'minecraft:poisonous_potato': { texture: 'textures/items/potato_poisonous', type: 'item' },
	'minecraft:poplar_boat': { texture: 'textures/items/poplar_boat', type: 'item' },
	'minecraft:poplar_chest_boat': { texture: 'textures/items/poplar_chest_boat', type: 'item' },
	'minecraft:poplar_sign': { texture: 'textures/items/poplar_sign', type: 'item' },
	'minecraft:popped_chorus_fruit': { texture: 'textures/items/chorus_fruit_popped', type: 'item' },
	'minecraft:potion': { texture: 'textures/items/potion_bottle_drinkable', type: 'item' },
	'minecraft:purple_bundle': { texture: 'textures/items/bundle_purple', type: 'item' },
	'minecraft:purple_cushion': { texture: 'textures/items/purple_cushion', type: 'item' },
	'minecraft:purple_harness': { texture: 'textures/items/harness/harness_purple', type: 'item' },
	'minecraft:red_bundle': { texture: 'textures/items/bundle_red', type: 'item' },
	'minecraft:red_cushion': { texture: 'textures/items/red_cushion', type: 'item' },
	'minecraft:red_harness': { texture: 'textures/items/harness/harness_red', type: 'item' },
	'minecraft:redstone': { texture: 'textures/items/redstone_dust', type: 'item' },
	'minecraft:slime_ball': { texture: 'textures/items/slimeball', type: 'item' },
	'minecraft:splash_potion': { texture: 'textures/items/potion_bottle_splash', type: 'item' },
	'minecraft:white_bundle': { texture: 'textures/items/bundle_white', type: 'item' },
	'minecraft:white_cushion': { texture: 'textures/items/white_cushion', type: 'item' },
	'minecraft:white_harness': { texture: 'textures/items/harness/harness_white', type: 'item' },
	'minecraft:yellow_bundle': { texture: 'textures/items/bundle_yellow', type: 'item' },
	'minecraft:yellow_cushion': { texture: 'textures/items/yellow_cushion', type: 'item' },
	'minecraft:yellow_harness': { texture: 'textures/items/harness/harness_yellow', type: 'item' },
	'minecraft:frame': { texture: 'textures/items/item_frame', type: 'item' },
	'minecraft:glow_frame': { texture: 'textures/items/glow_item_frame', type: 'item' },
	'minecraft:tropical_fish': { texture: 'textures/items/fish_clownfish_raw', type: 'item' },
	// â•â• add-ons â•â•
	// Kept whether or not the pack is loaded: an unused pin is never looked up,
	// but a missing one misrenders.
	'bedrockteams:setting': { texture: 'textures/items/banner_pattern', type: 'item' },
	'bedrockteams:tool': { texture: 'textures/items/nether_star', type: 'item' },
	'lildanlid:textmenu': { texture: 'textures/items/book_writable', type: 'item' },
	'namespace:id': { texture: 'path/or/typeId', type: 'item' },
	'pyrite_ingot:netherite_ingot': { texture: 'textures/items/pyrite/pyrite_ingot', type: 'item' },
	'tungsten_ingot:netherite_ingot': { texture: 'textures/items/tungsten/tungsten_ingot', type: 'item' },

	// â•â• OresPlus â•â•
	// Paths from the add-on's own textures/item_texture.json.
	'oresplus:adamantium_ingot': { texture: 'textures/items/adamantium/adamantium_ingot', type: 'item' },
	'oresplus:alexandrite': { texture: 'textures/items/alexandrite/alexandrite', type: 'item' },
	'oresplus:alexandrite_axe': { texture: 'textures/items/alexandrite/alexandrite_axe', type: 'item' },
	'oresplus:alexandrite_boots': { texture: 'textures/items/alexandrite/alexandrite_boots', type: 'item' },
	'oresplus:alexandrite_chestplate': { texture: 'textures/items/alexandrite/alexandrite_chestplate', type: 'item' },
	'oresplus:alexandrite_helmet': { texture: 'textures/items/alexandrite/alexandrite_helmet', type: 'item' },
	'oresplus:alexandrite_hoe': { texture: 'textures/items/alexandrite/alexandrite_hoe', type: 'item' },
	'oresplus:alexandrite_leggings': { texture: 'textures/items/alexandrite/alexandrite_leggings', type: 'item' },
	'oresplus:alexandrite_pickaxe': { texture: 'textures/items/alexandrite/alexandrite_pickaxe', type: 'item' },
	'oresplus:alexandrite_shovel': { texture: 'textures/items/alexandrite/alexandrite_shovel', type: 'item' },
	'oresplus:alexandrite_sword': { texture: 'textures/items/alexandrite/alexandrite_sword', type: 'item' },
	'oresplus:ambar': { texture: 'textures/items/white_diamond/essences/amber/amber', type: 'item' },
	'oresplus:ambar_boots': { texture: 'textures/items/white_diamond/essences/amber/amber_boots', type: 'item' },
	'oresplus:ambar_chestplate': { texture: 'textures/items/white_diamond/essences/amber/amber_chestplate', type: 'item' },
	'oresplus:ambar_helmet': { texture: 'textures/items/white_diamond/essences/amber/amber_helmet', type: 'item' },
	'oresplus:ambar_leggings': { texture: 'textures/items/white_diamond/essences/amber/amber_leggings', type: 'item' },
	'oresplus:amber_sword': { texture: 'textures/items/white_diamond/essences/amber/amber_sword', type: 'item' },
	'oresplus:angelic_boots': { texture: 'textures/items/white_diamond/essences/angelic/angelic_boots', type: 'item' },
	'oresplus:angelic_chestplate': { texture: 'textures/items/white_diamond/essences/angelic/angelic_chestplate', type: 'item' },
	'oresplus:angelic_gem': { texture: 'textures/items/white_diamond/essences/angelic/angelic_gem', type: 'item' },
	'oresplus:angelic_helmet': { texture: 'textures/items/white_diamond/essences/angelic/angelic_helmet', type: 'item' },
	'oresplus:angelic_leggings': { texture: 'textures/items/white_diamond/essences/angelic/angelic_leggings', type: 'item' },
	'oresplus:berries_pie': { texture: 'textures/items/berries_pie', type: 'item' },
	'oresplus:broken_gem': { texture: 'textures/items/broken_gem', type: 'item' },
	'oresplus:cooked_egg': { texture: 'textures/items/cooked_egg', type: 'item' },
	'oresplus:corrupted_crimtane_ingot': { texture: 'textures/items/crimnate/corrupted_crimtane_ingot', type: 'item' },
	'oresplus:crimtane_ingot': { texture: 'textures/items/crimnate/crimtane_ingot', type: 'item' },
	'oresplus:cryo_boots': { texture: 'textures/items/white_diamond/essences/cryo/cryo_boots', type: 'item' },
	'oresplus:cryo_chestplate': { texture: 'textures/items/white_diamond/essences/cryo/cryo_chestplate', type: 'item' },
	'oresplus:cryo_helmet': { texture: 'textures/items/white_diamond/essences/cryo/cryo_helmet', type: 'item' },
	'oresplus:cryo_leggings': { texture: 'textures/items/white_diamond/essences/cryo/cryo_leggings', type: 'item' },
	'oresplus:cryo_sword': { texture: 'textures/items/white_diamond/essences/cryo/cryo_sword', type: 'item' },
	'oresplus:desert_boots': { texture: 'textures/items/white_diamond/essences/desert/desert_boots', type: 'item' },
	'oresplus:desert_chestplate': { texture: 'textures/items/white_diamond/essences/desert/desert_chestplate', type: 'item' },
	'oresplus:desert_gem': { texture: 'textures/items/white_diamond/essences/desert/desert_gem', type: 'item' },
	'oresplus:desert_helmet': { texture: 'textures/items/white_diamond/essences/desert/desert_helmet', type: 'item' },
	'oresplus:desert_leggings': { texture: 'textures/items/white_diamond/essences/desert/desert_leggings', type: 'item' },
	'oresplus:diamond_bearded_axe': { texture: 'textures/items/diamond_bearded_axe', type: 'item' },
	'oresplus:diamond_katana': { texture: 'textures/items/diamond_katana', type: 'item' },
	'oresplus:diamond_knife': { texture: 'textures/items/diamond_knife', type: 'item' },
	'oresplus:electro_sword': { texture: 'textures/items/electro_sword', type: 'item' },
	'oresplus:emerald_axe': { texture: 'textures/items/emerald/emerald_axe', type: 'item' },
	'oresplus:emerald_boots': { texture: 'textures/items/emerald/emerald_boots', type: 'item' },
	'oresplus:emerald_chestplate': { texture: 'textures/items/emerald/emerald_chestplate', type: 'item' },
	'oresplus:emerald_helmet': { texture: 'textures/items/emerald/emerald_helmet', type: 'item' },
	'oresplus:emerald_hoe': { texture: 'textures/items/emerald/emerald_hoe', type: 'item' },
	'oresplus:emerald_leggings': { texture: 'textures/items/emerald/emerald_leggings', type: 'item' },
	'oresplus:emerald_pickaxe': { texture: 'textures/items/emerald/emerald_pickaxe', type: 'item' },
	'oresplus:emerald_shovel': { texture: 'textures/items/emerald/emerald_shovel', type: 'item' },
	'oresplus:emerald_sword': { texture: 'textures/items/emerald/emerald_sword', type: 'item' },
	'oresplus:end_boots': { texture: 'textures/items/white_diamond/essences/end/end_boots', type: 'item' },
	'oresplus:end_chestplate': { texture: 'textures/items/white_diamond/essences/end/end_chestplate', type: 'item' },
	'oresplus:end_gem': { texture: 'textures/items/white_diamond/essences/end/end_gem', type: 'item' },
	'oresplus:end_helmet': { texture: 'textures/items/white_diamond/essences/end/end_helmet', type: 'item' },
	'oresplus:end_leggings': { texture: 'textures/items/white_diamond/essences/end/end_leggings', type: 'item' },
	'oresplus:essence_angelic_gem': { texture: 'textures/items/white_diamond/essences/angelic/essence_angelic_gem', type: 'item' },
	'oresplus:essence_desert_gem': { texture: 'textures/items/white_diamond/essences/desert/essence_desert_gem', type: 'item' },
	'oresplus:essence_end_gem': { texture: 'textures/items/white_diamond/essences/end/essence_end_gem', type: 'item' },
	'oresplus:essence_infernal_gem': { texture: 'textures/items/white_diamond/essences/infernal/essence_infernal_gem', type: 'item' },
	'oresplus:essence_ocean_gem': { texture: 'textures/items/white_diamond/essences/ocean/essence_ocean_gem', type: 'item' },
	'oresplus:essence_spinel_gem': { texture: 'textures/items/white_diamond/essences/spinel/essence_spinel_gem', type: 'item' },
	'oresplus:essence_wither_gem': { texture: 'textures/items/wither/essence_wither_gem', type: 'item' },
	'oresplus:heillish_boots': { texture: 'textures/items/white_diamond/essences/demonic/demonic_boots', type: 'item' },
	'oresplus:heillish_chestplate': { texture: 'textures/items/white_diamond/essences/demonic/demonic_chestplate', type: 'item' },
	'oresplus:heillish_helmet': { texture: 'textures/items/white_diamond/essences/demonic/demonic_helmet', type: 'item' },
	'oresplus:heillish_leggings': { texture: 'textures/items/white_diamond/essences/demonic/demonic_leggings', type: 'item' },
	'oresplus:infernal_boots': { texture: 'textures/items/white_diamond/essences/infernal/infernal_boots', type: 'item' },
	'oresplus:infernal_chestplate': { texture: 'textures/items/white_diamond/essences/infernal/infernal_chestplate', type: 'item' },
	'oresplus:infernal_gem': { texture: 'textures/items/white_diamond/essences/infernal/infernal_gem', type: 'item' },
	'oresplus:infernal_helmet': { texture: 'textures/items/white_diamond/essences/infernal/infernal_helmet', type: 'item' },
	'oresplus:infernal_leggings': { texture: 'textures/items/white_diamond/essences/infernal/infernal_leggings', type: 'item' },
	'oresplus:infernal_pickaxe': { texture: 'textures/items/white_diamond/essences/infernal/infernal_pickaxe', type: 'item' },
	'oresplus:infernal_sword': { texture: 'textures/items/white_diamond/essences/infernal/infernal_sword', type: 'item' },
	'oresplus:jade': { texture: 'textures/items/white_diamond/essences/jade/jade', type: 'item' },
	'oresplus:jade_boots': { texture: 'textures/items/white_diamond/essences/jade/jade_boots', type: 'item' },
	'oresplus:jade_chestplate': { texture: 'textures/items/white_diamond/essences/jade/jade_chestplate', type: 'item' },
	'oresplus:jade_helmet': { texture: 'textures/items/white_diamond/essences/jade/jade_helmet', type: 'item' },
	'oresplus:jade_leggings': { texture: 'textures/items/white_diamond/essences/jade/jade_leggings', type: 'item' },
	'oresplus:mauve_boots': { texture: 'textures/items/moonstone/mauve_boots', type: 'item' },
	'oresplus:mauve_chestplate': { texture: 'textures/items/moonstone/mauve_chestplate', type: 'item' },
	'oresplus:mauve_helmet': { texture: 'textures/items/moonstone/mauve_helmet', type: 'item' },
	'oresplus:mauve_leggings': { texture: 'textures/items/moonstone/mauve_leggings', type: 'item' },
	'oresplus:moonstone': { texture: 'textures/items/moonstone/moonstone', type: 'item' },
	'oresplus:moonstone_axe': { texture: 'textures/items/moonstone/moonstone_axe', type: 'item' },
	'oresplus:moonstone_boots': { texture: 'textures/items/moonstone/moonstone_boots', type: 'item' },
	'oresplus:moonstone_chestplate': { texture: 'textures/items/moonstone/moonstone_chestplate', type: 'item' },
	'oresplus:moonstone_helmet': { texture: 'textures/items/moonstone/moonstone_helmet', type: 'item' },
	'oresplus:moonstone_hoe': { texture: 'textures/items/moonstone/moonstone_hoe', type: 'item' },
	'oresplus:moonstone_leggings': { texture: 'textures/items/moonstone/moonstone_leggings', type: 'item' },
	'oresplus:moonstone_pickaxe': { texture: 'textures/items/moonstone/moonstone_pickaxe', type: 'item' },
	'oresplus:moonstone_shovel': { texture: 'textures/items/moonstone/moonstone_shovel', type: 'item' },
	'oresplus:moonstone_sword': { texture: 'textures/items/moonstone/moonstone_sword', type: 'item' },
	'oresplus:mythril': { texture: 'textures/items/mythril/mythril', type: 'item' },
	'oresplus:netherite_bearded_axe': { texture: 'textures/items/netherite_bearded_axe', type: 'item' },
	'oresplus:netherite_katana': { texture: 'textures/items/netherite_katana', type: 'item' },
	'oresplus:netherite_knife': { texture: 'textures/items/netherite_knife', type: 'item' },
	'oresplus:ocean_boots': { texture: 'textures/items/white_diamond/essences/ocean/ocean_boots', type: 'item' },
	'oresplus:ocean_chestplate': { texture: 'textures/items/white_diamond/essences/ocean/ocean_chestplate', type: 'item' },
	'oresplus:ocean_gem': { texture: 'textures/items/white_diamond/essences/ocean/ocean_gem', type: 'item' },
	'oresplus:ocean_helmet': { texture: 'textures/items/white_diamond/essences/ocean/ocean_helmet', type: 'item' },
	'oresplus:ocean_leggings': { texture: 'textures/items/white_diamond/essences/ocean/ocean_leggings', type: 'item' },
	'oresplus:purified_crimtane_ingot': { texture: 'textures/items/crimnate/purified_crimtane_ingot', type: 'item' },
	'oresplus:pyrite_axe': { texture: 'textures/items/pyrite/pyrite_axe', type: 'item' },
	'oresplus:pyrite_bearded_axe': { texture: 'textures/items/pyrite/pyrite_bearded_axe', type: 'item' },
	'oresplus:pyrite_boots': { texture: 'textures/items/pyrite/pyrite_boots', type: 'item' },
	'oresplus:pyrite_chestplate': { texture: 'textures/items/pyrite/pyrite_chestplate', type: 'item' },
	'oresplus:pyrite_helmet': { texture: 'textures/items/pyrite/pyrite_helmet', type: 'item' },
	'oresplus:pyrite_hoe': { texture: 'textures/items/pyrite/pyrite_hoe', type: 'item' },
	'oresplus:pyrite_katana': { texture: 'textures/items/pyrite/pyrite_katana', type: 'item' },
	'oresplus:pyrite_knife': { texture: 'textures/items/pyrite/pyrite_knife', type: 'item' },
	'oresplus:pyrite_leggings': { texture: 'textures/items/pyrite/pyrite_leggings', type: 'item' },
	'oresplus:pyrite_pickaxe': { texture: 'textures/items/pyrite/pyrite_pickaxe', type: 'item' },
	'oresplus:pyrite_shovel': { texture: 'textures/items/pyrite/pyrite_shovel', type: 'item' },
	'oresplus:pyrite_sword': { texture: 'textures/items/pyrite/pyrite_sword', type: 'item' },
	'oresplus:raw_rose_gold': { texture: 'textures/items/rose_gold/raw_rose_gold', type: 'item' },
	'oresplus:raw_silver': { texture: 'textures/items/silver/raw_silver', type: 'item' },
	'oresplus:raw_tane': { texture: 'textures/items/tane/raw_tane', type: 'item' },
	'oresplus:raw_titanium': { texture: 'textures/items/titanium/raw_titanium', type: 'item' },
	'oresplus:raw_tungsten': { texture: 'textures/items/tungsten/raw_tungsten', type: 'item' },
	'oresplus:reinforced_ruby_axe': { texture: 'textures/items/ruby/reinforced_ruby_axe', type: 'item' },
	'oresplus:reinforced_ruby_boots': { texture: 'textures/items/ruby/reinforced_ruby_boots', type: 'item' },
	'oresplus:reinforced_ruby_chestplate': { texture: 'textures/items/ruby/reinforced_ruby_chestplate', type: 'item' },
	'oresplus:reinforced_ruby_helmet': { texture: 'textures/items/ruby/reinforced_ruby_helmet', type: 'item' },
	'oresplus:reinforced_ruby_hoe': { texture: 'textures/items/ruby/reinforced_ruby_hoe', type: 'item' },
	'oresplus:reinforced_ruby_leggings': { texture: 'textures/items/ruby/reinforced_ruby_leggings', type: 'item' },
	'oresplus:reinforced_ruby_pickaxe': { texture: 'textures/items/ruby/reinforced_ruby_pickaxe', type: 'item' },
	'oresplus:reinforced_ruby_shovel': { texture: 'textures/items/ruby/reinforced_ruby_shovel', type: 'item' },
	'oresplus:reinforced_ruby_sword': { texture: 'textures/items/ruby/reinforced_ruby_sword', type: 'item' },
	'oresplus:reinforced_titanium_axe': { texture: 'textures/items/titanium/reinforced_titanium_axe', type: 'item' },
	'oresplus:reinforced_titanium_boots': { texture: 'textures/items/titanium/reinforced_titanium_boots', type: 'item' },
	'oresplus:reinforced_titanium_chestplate': { texture: 'textures/items/titanium/reinforced_titanium_chestplate', type: 'item' },
	'oresplus:reinforced_titanium_helmet': { texture: 'textures/items/titanium/reinforced_titanium_helmet', type: 'item' },
	'oresplus:reinforced_titanium_hoe': { texture: 'textures/items/titanium/reinforced_titanium_hoe', type: 'item' },
	'oresplus:reinforced_titanium_leggings': { texture: 'textures/items/titanium/reinforced_titanium_leggings', type: 'item' },
	'oresplus:reinforced_titanium_pickaxe': { texture: 'textures/items/titanium/reinforced_titanium_pickaxe', type: 'item' },
	'oresplus:reinforced_titanium_shovel': { texture: 'textures/items/titanium/reinforced_titanium_shovel', type: 'item' },
	'oresplus:reinforced_titanium_sword': { texture: 'textures/items/titanium/reinforced_titanium_sword', type: 'item' },
	'oresplus:rose_gold_axe': { texture: 'textures/items/rose_gold/rose_gold_axe', type: 'item' },
	'oresplus:rose_gold_boots': { texture: 'textures/items/rose_gold/rose_gold_boots', type: 'item' },
	'oresplus:rose_gold_chestplate': { texture: 'textures/items/rose_gold/rose_gold_chestplate', type: 'item' },
	'oresplus:rose_gold_helmet': { texture: 'textures/items/rose_gold/rose_gold_helmet', type: 'item' },
	'oresplus:rose_gold_hoe': { texture: 'textures/items/rose_gold/rose_gold_hoe', type: 'item' },
	'oresplus:rose_gold_ingot': { texture: 'textures/items/rose_gold/rose_gold_ingot', type: 'item' },
	'oresplus:rose_gold_leggings': { texture: 'textures/items/rose_gold/rose_gold_leggings', type: 'item' },
	'oresplus:rose_gold_pickaxe': { texture: 'textures/items/rose_gold/rose_gold_pickaxe', type: 'item' },
	'oresplus:rose_gold_shovel': { texture: 'textures/items/rose_gold/rose_gold_shovel', type: 'item' },
	'oresplus:rose_gold_sword': { texture: 'textures/items/rose_gold/rose_gold_sword', type: 'item' },
	'oresplus:rose_quartz': { texture: 'textures/items/rose_quartz/rose_quartz', type: 'item' },
	'oresplus:ruby': { texture: 'textures/items/ruby/ruby', type: 'item' },
	'oresplus:ruby_axe': { texture: 'textures/items/ruby/ruby_axe', type: 'item' },
	'oresplus:ruby_boots': { texture: 'textures/items/ruby/ruby_boots', type: 'item' },
	'oresplus:ruby_chestplate': { texture: 'textures/items/ruby/ruby_chestplate', type: 'item' },
	'oresplus:ruby_helmet': { texture: 'textures/items/ruby/ruby_helmet', type: 'item' },
	'oresplus:ruby_hoe': { texture: 'textures/items/ruby/ruby_hoe', type: 'item' },
	'oresplus:ruby_leggings': { texture: 'textures/items/ruby/ruby_leggings', type: 'item' },
	'oresplus:ruby_pickaxe': { texture: 'textures/items/ruby/ruby_pickaxe', type: 'item' },
	'oresplus:ruby_shovel': { texture: 'textures/items/ruby/ruby_shovel', type: 'item' },
	'oresplus:ruby_sword': { texture: 'textures/items/ruby/ruby_sword', type: 'item' },
	'oresplus:sapphire': { texture: 'textures/items/sapphire/sapphire', type: 'item' },
	'oresplus:sapphire_axe': { texture: 'textures/items/sapphire/sapphire_axe', type: 'item' },
	'oresplus:sapphire_boots': { texture: 'textures/items/sapphire/sapphire_boots', type: 'item' },
	'oresplus:sapphire_chestplate': { texture: 'textures/items/sapphire/sapphire_chestplate', type: 'item' },
	'oresplus:sapphire_helmet': { texture: 'textures/items/sapphire/sapphire_helmet', type: 'item' },
	'oresplus:sapphire_hoe': { texture: 'textures/items/sapphire/sapphire_hoe', type: 'item' },
	'oresplus:sapphire_leggings': { texture: 'textures/items/sapphire/sapphire_leggings', type: 'item' },
	'oresplus:sapphire_pickaxe': { texture: 'textures/items/sapphire/sapphire_pickaxe', type: 'item' },
	'oresplus:sapphire_shovel': { texture: 'textures/items/sapphire/sapphire_shovel', type: 'item' },
	'oresplus:sapphire_sword': { texture: 'textures/items/sapphire/sapphire_sword', type: 'item' },
	'oresplus:shulker_fruit': { texture: 'textures/items/shulker_fruit', type: 'item' },
	'oresplus:silver_bearded_axe': { texture: 'textures/items/silver/silver_bearded_axe', type: 'item' },
	'oresplus:silver_ingot': { texture: 'textures/items/silver/silver_ingot', type: 'item' },
	'oresplus:silver_katana': { texture: 'textures/items/silver/silver_katana', type: 'item' },
	'oresplus:silver_knife': { texture: 'textures/items/silver/silver_knife', type: 'item' },
	'oresplus:silver_nugget': { texture: 'textures/items/silver/silver_nugget', type: 'item' },
	'oresplus:skull_sword': { texture: 'textures/items/skull_sword', type: 'item' },
	'oresplus:spinel_boots': { texture: 'textures/items/white_diamond/essences/spinel/spinel_boots', type: 'item' },
	'oresplus:spinel_chestplate': { texture: 'textures/items/white_diamond/essences/spinel/spinel_chestplate', type: 'item' },
	'oresplus:spinel_gem': { texture: 'textures/items/white_diamond/essences/spinel/spinel_gem', type: 'item' },
	'oresplus:spinel_helmet': { texture: 'textures/items/white_diamond/essences/spinel/spinel_helmet', type: 'item' },
	'oresplus:spinel_leggings': { texture: 'textures/items/white_diamond/essences/spinel/spinel_leggings', type: 'item' },
	'oresplus:steel_boots': { texture: 'textures/items/steel/steel_boots', type: 'item' },
	'oresplus:steel_chestplate': { texture: 'textures/items/steel/steel_chestplate', type: 'item' },
	'oresplus:steel_helmet': { texture: 'textures/items/steel/steel_helmet', type: 'item' },
	'oresplus:steel_ingot': { texture: 'textures/items/steel/steel_ingot', type: 'item' },
	'oresplus:steel_leggings': { texture: 'textures/items/steel/steel_leggings', type: 'item' },
	'oresplus:steel_rod': { texture: 'textures/items/steel/steel_rod', type: 'item' },
	'oresplus:super_meat_stew': { texture: 'textures/items/super_meat_stew', type: 'item' },
	'oresplus:tane_ingot': { texture: 'textures/items/tane/tane_ingot', type: 'item' },
	'oresplus:titanium_ingot': { texture: 'textures/items/titanium/titanium_ingot', type: 'item' },
	'oresplus:tungsten_axe': { texture: 'textures/items/tungsten/tungsten_axe', type: 'item' },
	'oresplus:tungsten_boots': { texture: 'textures/items/tungsten/tungsten_boots', type: 'item' },
	'oresplus:tungsten_chestplate': { texture: 'textures/items/tungsten/tungsten_chestplate', type: 'item' },
	'oresplus:tungsten_helmet': { texture: 'textures/items/tungsten/tungsten_helmet', type: 'item' },
	'oresplus:tungsten_hoe': { texture: 'textures/items/tungsten/tungsten_hoe', type: 'item' },
	'oresplus:tungsten_leggings': { texture: 'textures/items/tungsten/tungsten_leggings', type: 'item' },
	'oresplus:tungsten_pickaxe': { texture: 'textures/items/tungsten/tungsten_pickaxe', type: 'item' },
	'oresplus:tungsten_shovel': { texture: 'textures/items/tungsten/tungsten_shovel', type: 'item' },
	'oresplus:tungsten_sword': { texture: 'textures/items/tungsten/tungsten_sword', type: 'item' },
	'oresplus:white_diamond': { texture: 'textures/items/white_diamond/white_diamond', type: 'item' },
	'oresplus:white_diamond_boots': { texture: 'textures/items/white_diamond/white_diamond_boots', type: 'item' },
	'oresplus:white_diamond_chestplate': { texture: 'textures/items/white_diamond/white_diamond_chestplate', type: 'item' },
	'oresplus:white_diamond_helmet': { texture: 'textures/items/white_diamond/white_diamond_helmet', type: 'item' },
	'oresplus:white_diamond_leggings': { texture: 'textures/items/white_diamond/white_diamond_leggings', type: 'item' },
	'oresplus:white_diamond_sword': { texture: 'textures/items/white_diamond/white_diamond_sword', type: 'item' },
	'oresplus:wither_gem': { texture: 'textures/items/wither/wither_gem', type: 'item' },
	'oresplus:wither_shard': { texture: 'textures/items/wither/wither_shard', type: 'item' },
	'oresplus:wither_sword': { texture: 'textures/items/wither/wither_sword', type: 'item' },
};

// Vanilla item ids at or above 256 get shifted by however many CUSTOM items the
// world has registered, because Bedrock hands add-on items ids out of that same
// range and pushes the vanilla ones up. forms.js applies this as the offset.
//
// Only genuinely custom items may be counted. The 'minecraft:' entries in
// custom_content above are texture-path OVERRIDES for icons the numeric table
// gets wrong - they occupy no slot in the item registry. Counting them (as this
// line used to) inflated the offset and displaced every vanilla item that had no
// override of its own, which is why auction listings showed the wrong picture.
//
// It was also self-worsening: every vanilla icon "fixed" by adding it here
// pushed one more slot out of alignment for everything else, so each round of
// fixes broke more items than it repaired.
// Counted against the ids the game actually registered, not against this table.
// The table pins every add-on we might ever run alongside (OresPlus and friends)
// so one build works in any world, but a pin for a pack that is not loaded
// occupies no registry slot - counting it would shift vanilla icons in exactly
// the worlds that do not have the add-on.
//
// Deliberately lazy. ItemTypes.getAll() cannot be called while the module is
// still being evaluated: early startup is outside a valid execution context and
// the call throws, so a module-level count silently fell back to the table and
// reintroduced the very shift it exists to prevent. The first slot is not drawn
// until a player opens a menu, by which point the registry is readable.
const CUSTOM_ITEM_IDS = Object.entries(custom_content)
	.filter(([id, value]) => value.type === 'item' && !id.startsWith('minecraft:'))
	.map(([id]) => id);

let cachedCustomCount = null;

export function customItemCount() {
	if (cachedCustomCount !== null) return cachedCustomCount;
	try {
		const registered = new Set(mc.ItemTypes.getAll().map(t => t.id));
		cachedCustomCount = CUSTOM_ITEM_IDS.filter(id => registered.has(id)).length;
	} catch {
		return CUSTOM_ITEM_IDS.length;   // not cached: retry once the registry is up
	}
	return cachedCustomCount;
}
export const custom_content_keys = new Set(Object.keys(custom_content));

/** Available chest sizes. Each maps to [ui_title_flag, slot_count]. */
export const CHEST_UI_SIZES = new Map([
	['single', ['§c§h§e§s§t§2§7§r', 27]], ['small',  ['§c§h§e§s§t§2§7§r', 27]],
	['double', ['§c§h§e§s§t§5§4§r', 54]], ['large',  ['§c§h§e§s§t§5§4§r', 54]],
	['1',  ['§c§h§e§s§t§0§1§r',  1]],
	['5',  ['§c§h§e§s§t§0§5§r',  5]],
	['9',  ['§c§h§e§s§t§0§9§r',  9]],
	['18', ['§c§h§e§s§t§1§8§r', 18]],
	['27', ['§c§h§e§s§t§2§7§r', 27]],
	['36', ['§c§h§e§s§t§3§6§r', 36]],
	['45', ['§c§h§e§s§t§4§5§r', 45]],
	['54', ['§c§h§e§s§t§5§4§r', 54]],
	[1,  ['§c§h§e§s§t§0§1§r',  1]],
	[5,  ['§c§h§e§s§t§0§5§r',  5]],
	[9,  ['§c§h§e§s§t§0§9§r',  9]],
	[18, ['§c§h§e§s§t§1§8§r', 18]],
	[27, ['§c§h§e§s§t§2§7§r', 27]],
	[36, ['§c§h§e§s§t§3§6§r', 36]],
	[45, ['§c§h§e§s§t§4§5§r', 45]],
	[54, ['§c§h§e§s§t§5§4§r', 54]],
]);
